name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build muslCross --file muslCross/Dockerfile --tag mfearsgov/musl-cross:latest
        docker build ubuntuTest --file ubuntuTest/Dockerfile --tag mfearsgov/test:ubuntu
        docker build md2pdf --file md2pdf/Dockerfile --tag mfearsgov/md2pdf:latest

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username mfearsgov --password-stdin

    - name: Push Docker Images
      run: |
        docker push mfearsgov/musl-cross:latest
        docker push mfearsgov/test:ubuntu
        docker push mfearsgov/md2pdf:latest


